from fpdf import FPDF
from datetime import datetime


def generate_pdf(report: dict, portfolio: dict) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- Cover page ---
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 28)
    pdf.cell(0, 40, "", ln=True)
    pdf.cell(0, 15, "Portfolio Research Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 10, f"Generated: {datetime.now().strftime('%B %d, %Y %I:%M %p')}", ln=True, align="C")
    pdf.cell(0, 10, "", ln=True)

    pdf.set_font("Helvetica", "B", 16)
    health = report.get("health_score", "N/A")
    pdf.cell(0, 12, f"Portfolio Health Score: {health}/100", ln=True, align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Recommendation: {report.get('overall_recommendation', 'N/A')}", ln=True, align="C")

    pdf.cell(0, 15, "", ln=True)
    total_val = portfolio.get("total_value", 0)
    total_inv = portfolio.get("total_invested", 0)
    total_pnl = portfolio.get("total_pnl_pct", 0)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, f"Total Value: Rs. {total_val:,.2f}", ln=True, align="C")
    pdf.cell(0, 8, f"Total Invested: Rs. {total_inv:,.2f}", ln=True, align="C")
    pdf.cell(0, 8, f"Overall P&L: {total_pnl:+.2f}%", ln=True, align="C")

    # --- Executive Summary ---
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, "Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7, report.get("executive_summary", "N/A"))
    pdf.cell(0, 5, "", ln=True)

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Tomorrow's Outlook", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7, report.get("tomorrow_outlook", "N/A"))
    pdf.cell(0, 5, "", ln=True)

    # --- Stock Analysis ---
    for stock in report.get("stocks", []):
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 12, f"{stock.get('ticker', 'N/A')} - {stock.get('company_name', '')}", ln=True)

        pdf.set_font("Helvetica", "B", 12)
        rating = stock.get("analyst_rating", "HOLD")
        pdf.cell(0, 8, f"Rating: {rating} | Action: {stock.get('action', 'HOLD')}", ln=True)

        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 7, f"Reason: {stock.get('rating_reason', 'N/A')}")
        pdf.cell(0, 3, "", ln=True)

        tomorrow = stock.get("tomorrow_range", {})
        pdf.cell(0, 7, f"Tomorrow Range: Rs. {tomorrow.get('low', 0)} - Rs. {tomorrow.get('high', 0)} | Direction: {stock.get('tomorrow_direction', 'N/A')}", ln=True)

        if stock.get("key_catalysts"):
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 8, "Key Catalysts:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            for c in stock["key_catalysts"]:
                pdf.cell(0, 6, f"  + {c}", ln=True)

        if stock.get("key_risks"):
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 8, "Key Risks:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            for r in stock["key_risks"]:
                pdf.cell(0, 6, f"  - {r}", ln=True)

        pdf.cell(0, 5, "", ln=True)
        pdf.set_font("Helvetica", "I", 10)
        pdf.multi_cell(0, 6, f"Action: {stock.get('action_reason', 'N/A')}")

    # --- Opportunities & Risks ---
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, "Top Opportunities", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for i, opp in enumerate(report.get("top_opportunities", []), 1):
        pdf.cell(0, 7, f"  {i}. {opp}", ln=True)

    pdf.cell(0, 8, "", ln=True)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, "Top Risks", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for i, risk in enumerate(report.get("top_risks", []), 1):
        pdf.cell(0, 7, f"  {i}. {risk}", ln=True)

    pdf.cell(0, 8, "", ln=True)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, "Rebalancing Suggestions", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for i, sug in enumerate(report.get("rebalancing_suggestions", []), 1):
        pdf.cell(0, 7, f"  {i}. {sug}", ln=True)

    # --- Disclaimer ---
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 12, "Disclaimer", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6,
        "AI-generated analysis for informational purposes only. Not financial advice. "
        "This report was generated by an AI model and should not be used as the sole basis "
        "for any investment decision. Past performance is not indicative of future results. "
        "Always consult a qualified financial advisor before making investment decisions. "
        "The authors and developers of this tool accept no liability for any losses incurred "
        "as a result of using this report."
    )

    return pdf.output()
